export const myData = [
    {
        id: 0,
        firstName: "Chastity",
        lastName: "Speir",
        avatar: "https://res.cloudinary.com/tinyfac-es/image/upload/w_1024,h_1024,c_fit/v1627199936/facebook/z5jkejtavbbalgw8ho9a.jpg",
        image: "https://picsum.photos/600?random=159",
        favorite: false,
        likes: 5643,
        dislikes: 112,
        quote: "The biggest room in the world is room for improvement.",
    },
    {
        id: 1,
        firstName: "Dawna",
        lastName: "Lapadula",
        avatar: "https://res.cloudinary.com/tinyfac-es/image/upload/w_1024,h_1024,c_fit/v1627200035/facebook/wnduuupvqmpay73ievyg.jpg",
        image: "https://picsum.photos/600?random=94",
        favorite: false,
        likes: 5871,
        dislikes: 129,
        quote: "There’s power in looking silly and not caring that you do.",
    },
    {
        id: 2,
        firstName: "Lazlo",
        lastName: "Grippi",
        avatar: "https://res.cloudinary.com/tinyfac-es/image/upload/w_1024,h_1024,c_fit/v1627199986/facebook/cyritfbaorr1wxaqoxy3.jpg",
        image: "https://picsum.photos/600?random=196",
        favorite: false,
        likes: 4778,
        dislikes: 266,
        quote: "Whether you think you can or you think you can't, you are right.",
    },
    {
        id: 3,
        firstName: "Neall",
        lastName: "Awkard",
        avatar: "https://res.cloudinary.com/tinyfac-es/image/upload/w_1024,h_1024,c_fit/v1627200015/facebook/ah8r4kdkc0ieonk4wfko.jpg",
        image: "https://picsum.photos/600?random=297",
        favorite: false,
        likes: 2577,
        dislikes: 446,
        quote: "You can't blame gravity for falling in love.",
    },
    {
        id: 4,
        firstName: "Lucy",
        lastName: "Cardona",
        avatar: "https://res.cloudinary.com/tinyfac-es/image/upload/w_1024,h_1024,c_fit/v1627200008/facebook/t8tobjxzavpi68dus04t.jpg",
        image: "https://picsum.photos/600?random=235",
        favorite: false,
        likes: 6593,
        dislikes: 360,
        quote: "To be wronged is nothing unless you continue to remember it.",
    },
    {
        id: 5,
        firstName: "Melody",
        lastName: "Harjochee",
        avatar: "https://res.cloudinary.com/tinyfac-es/image/upload/w_1024,h_1024,c_fit/v1627199987/facebook/yqbfbicwl4rygivfvxv7.jpg",
        image: "https://picsum.photos/600?random=232",
        favorite: false,
        likes: 2636,
        dislikes: 260,
        quote: "Truth is powerful and it prevails.",
    },
    {
        id: 6,
        firstName: "Tanny",
        lastName: "Ashton",
        avatar: "https://res.cloudinary.com/tinyfac-es/image/upload/w_1024,h_1024,c_fit/v1627200051/facebook/ho0naqfmcovwfqozfljo.jpg",
        image: "https://picsum.photos/600?random=244",
        favorite: false,
        likes: 4649,
        dislikes: 285,
        quote: "Don't talk about what you have done or what you are going to do.",
    },
    {
        id: 7,
        firstName: "Sharai",
        lastName: "Deslatte",
        avatar: "https://res.cloudinary.com/tinyfac-es/image/upload/w_1024,h_1024,c_fit/v1627199953/facebook/hxfzz3fs8ancpuqdahtk.jpg",
        image: "https://picsum.photos/600?random=225",
        favorite: false,
        likes: 3079,
        dislikes: 281,
        quote: "Make it your habit not to be critical about small things.",
    },
    {
        id: 8,
        firstName: "Norma",
        lastName: "Lindenfelser",
        avatar: "https://res.cloudinary.com/tinyfac-es/image/upload/w_1024,h_1024,c_fit/v1627200005/facebook/ngghczzxx6hgfvitsvz2.jpg",
        image: "https://picsum.photos/600?random=95",
        favorite: false,
        likes: 6752,
        dislikes: 468,
        quote: "Silence is the sleep that nourishes wisdom.",
    },
    {
        id: 9,
        firstName: "Melody",
        lastName: "Harjochee",
        avatar: "https://res.cloudinary.com/tinyfac-es/image/upload/w_1024,h_1024,c_fit/v1627199987/facebook/yqbfbicwl4rygivfvxv7.jpg",
        image: "https://picsum.photos/600?random=31",
        favorite: false,
        likes: 3744,
        dislikes: 118,
        quote: "Friendship, like credit, is highest when it is not used.",
    },
    {
        id: 10,
        firstName: "Bruno",
        lastName: "Astry",
        avatar: "https://res.cloudinary.com/tinyfac-es/image/upload/w_1024,h_1024,c_fit/v1627200071/facebook/g3kqcm6xpfg4o02caty8.jpg",
        image: "https://picsum.photos/600?random=58",
        favorite: false,
        likes: 2557,
        dislikes: 275,
        quote: "Friendship increases in visiting friends, but in visiting them seldom.",
    },
    {
        id: 11,
        firstName: "Jonny",
        lastName: "Lacrue",
        avatar: "https://res.cloudinary.com/tinyfac-es/image/upload/w_1024,h_1024,c_fit/v1627200011/facebook/ew3gzts99dtl2s4vzwjj.jpg",
        image: "https://picsum.photos/600?random=22",
        favorite: false,
        likes: 3240,
        dislikes: 199,
        quote: "In the middle of every difficulty lies opportunity.",
    },
    {
        id: 12,
        firstName: "Roxanne",
        lastName: "Mcleese",
        avatar: "https://res.cloudinary.com/tinyfac-es/image/upload/w_1024,h_1024,c_fit/v1627199963/facebook/x88dl9hfzhvtsly9r546.jpg",
        image: "https://picsum.photos/600?random=275",
        favorite: false,
        likes: 3804,
        dislikes: 341,
        quote: "The only real failure in life is not to be true to the best one knows.",
    },
    {
        id: 13,
        firstName: "Berthe",
        lastName: "Hrobsky",
        avatar: "https://res.cloudinary.com/tinyfac-es/image/upload/w_1024,h_1024,c_fit/v1627199943/facebook/ggfttwzxpakh4mfh3oy2.jpg",
        image: "https://picsum.photos/600?random=128",
        favorite: false,
        likes: 6699,
        dislikes: 432,
        quote: "A man who doesn't trust himself can never really trust anyone else.",
    },
    {
        id: 14,
        firstName: "Sharai",
        lastName: "Deslatte",
        avatar: "https://res.cloudinary.com/tinyfac-es/image/upload/w_1024,h_1024,c_fit/v1627199953/facebook/hxfzz3fs8ancpuqdahtk.jpg",
        image: "https://picsum.photos/600?random=96",
        favorite: false,
        likes: 5712,
        dislikes: 85,
        quote: "Be here now. Be someplace else later. Is that so complicated?",
    },
    {
        id: 15,
        firstName: "Jameson",
        lastName: "Bologna",
        avatar: "https://res.cloudinary.com/tinyfac-es/image/upload/w_1024,h_1024,c_fit/v1627199928/facebook/dqqpq30cor22i9t9whwd.jpg",
        image: "https://picsum.photos/600?random=277",
        favorite: false,
        likes: 2752,
        dislikes: 129,
        quote: "You must welcome change as the rule but not as your ruler.",
    },
    {
        id: 16,
        firstName: "Sharai",
        lastName: "Deslatte",
        avatar: "https://res.cloudinary.com/tinyfac-es/image/upload/w_1024,h_1024,c_fit/v1627199953/facebook/hxfzz3fs8ancpuqdahtk.jpg",
        image: "https://picsum.photos/600?random=74",
        favorite: false,
        likes: 4685,
        dislikes: 320,
        quote: "Just trust yourself, then you will know how to live.",
    },
    {
        id: 17,
        firstName: "Daryl",
        lastName: "Ferrini",
        avatar: "https://res.cloudinary.com/tinyfac-es/image/upload/w_1024,h_1024,c_fit/v1627200066/facebook/yf6lqypnuf7mvbdd9pyt.jpg",
        image: "https://picsum.photos/600?random=104",
        favorite: false,
        likes: 5762,
        dislikes: 352,
        quote: "He who knows others is wise. He who knows himself is enlightened.",
    },
    {
        id: 18,
        firstName: "Oral",
        lastName: "Person",
        avatar: "https://res.cloudinary.com/tinyfac-es/image/upload/w_1024,h_1024,c_fit/v1627199949/facebook/tu4ja0pkwa9butxgg1ck.jpg",
        image: "https://picsum.photos/600?random=107",
        favorite: false,
        likes: 4871,
        dislikes: 59,
        quote: "All our knowledge has its origins in our perceptions.",
    },
    {
        id: 19,
        firstName: "Tiff",
        lastName: "Treen",
        avatar: "https://res.cloudinary.com/tinyfac-es/image/upload/w_1024,h_1024,c_fit/v1627199961/facebook/tm4a7psa2yyztvgs8dox.jpg",
        image: "https://picsum.photos/600?random=278",
        favorite: false,
        likes: 4876,
        dislikes: 241,
        quote: "Nothing will work unless you do.",
    },
    {
        id: 20,
        firstName: "Gwenni",
        lastName: "Demeritte",
        avatar: "https://res.cloudinary.com/tinyfac-es/image/upload/w_1024,h_1024,c_fit/v1627199963/facebook/xiczkgj5icszhefygihy.jpg",
        image: "https://picsum.photos/600?random=248",
        favorite: false,
        likes: 6446,
        dislikes: 383,
        quote: "Fears are nothing more than a state of mind.",
    },
    {
        id: 21,
        firstName: "Tanny",
        lastName: "Ashton",
        avatar: "https://res.cloudinary.com/tinyfac-es/image/upload/w_1024,h_1024,c_fit/v1627200051/facebook/ho0naqfmcovwfqozfljo.jpg",
        image: "https://picsum.photos/600?random=93",
        favorite: false,
        likes: 5122,
        dislikes: 413,
        quote: "Thought is the blossom; language the bud; action the fruit behind it.",
    },
    {
        id: 22,
        firstName: "Zebedee",
        lastName: "Busenius",
        avatar: "https://res.cloudinary.com/tinyfac-es/image/upload/w_1024,h_1024,c_fit/v1630596435/facebook/rw9x7plxcpgwtzmk6p37.jpg",
        image: "https://picsum.photos/600?random=103",
        favorite: false,
        likes: 3382,
        dislikes: 69,
        quote: "Argue for your limitations, and sure enough they're yours.",
    },
    {
        id: 23,
        firstName: "Rosabelle",
        lastName: "Stagers",
        avatar: "https://res.cloudinary.com/tinyfac-es/image/upload/w_1024,h_1024,c_fit/v1627200025/facebook/ox8s35tv185lb7dw8el0.jpg",
        image: "https://picsum.photos/600?random=93",
        favorite: false,
        likes: 3792,
        dislikes: 259,
        quote: "He that is giddy thinks the world turns round.",
    },
    {
        id: 24,
        firstName: "Melody",
        lastName: "Harjochee",
        avatar: "https://res.cloudinary.com/tinyfac-es/image/upload/w_1024,h_1024,c_fit/v1627199987/facebook/yqbfbicwl4rygivfvxv7.jpg",
        image: "https://picsum.photos/600?random=200",
        favorite: false,
        likes: 5853,
        dislikes: 314,
        quote: "The greater our knowledge increases the more our ignorance unfolds.",
    },
    {
        id: 25,
        firstName: "Rosalynd",
        lastName: "Ibbetson",
        avatar: "https://res.cloudinary.com/tinyfac-es/image/upload/w_1024,h_1024,c_fit/v1627200051/facebook/s3zdxnpt0cnfkiklnbzg.jpg",
        image: "https://picsum.photos/600?random=72",
        favorite: false,
        likes: 4878,
        dislikes: 266,
        quote: "Mistakes are the usual bridge between inexperience and wisdom.",
    },
    {
        id: 26,
        firstName: "Norma",
        lastName: "Lindenfelser",
        avatar: "https://res.cloudinary.com/tinyfac-es/image/upload/w_1024,h_1024,c_fit/v1627200005/facebook/ngghczzxx6hgfvitsvz2.jpg",
        image: "https://picsum.photos/600?random=139",
        favorite: false,
        likes: 5275,
        dislikes: 154,
        quote: "Our character is what we do when we think no one is looking.",
    },
    {
        id: 27,
        firstName: "Sheilakathryn",
        lastName: "Fernandz",
        avatar: "https://res.cloudinary.com/tinyfac-es/image/upload/w_1024,h_1024,c_fit/v1627200025/facebook/aopuw2ptal2kt9cf3hcp.jpg",
        image: "https://picsum.photos/600?random=2",
        favorite: false,
        likes: 6646,
        dislikes: 163,
        quote: "Friendship is a very taxing and arduous form of leisure activity.",
    },
    {
        id: 28,
        firstName: "Celinda",
        lastName: "Earthman",
        avatar: "https://res.cloudinary.com/tinyfac-es/image/upload/w_1024,h_1024,c_fit/v1627199941/facebook/nqumlvjqmyglab9obcbo.jpg",
        image: "https://picsum.photos/600?random=207",
        favorite: false,
        likes: 6843,
        dislikes: 318,
        quote: "If you smile when no one else is around, you really mean it.",
    },
    {
        id: 29,
        firstName: "Lissi",
        lastName: "Tocchio",
        avatar: "https://res.cloudinary.com/tinyfac-es/image/upload/w_1024,h_1024,c_fit/v1627200002/facebook/e6nfzs1jsv9ngzjivheb.jpg",
        image: "https://picsum.photos/600?random=113",
        favorite: false,
        likes: 2997,
        dislikes: 306,
        quote: "A jug fills drop by drop.",
    },
    {
        id: 30,
        firstName: "Pepi",
        lastName: "Hutchings",
        avatar: "https://res.cloudinary.com/tinyfac-es/image/upload/w_1024,h_1024,c_fit/v1627199970/facebook/g1vbmsmohrypg3aqt8ig.jpg",
        image: "https://picsum.photos/600?random=236",
        favorite: false,
        likes: 5858,
        dislikes: 229,
        quote: "What worries you masters you.",
    },
    {
        id: 31,
        firstName: "Melody",
        lastName: "Harjochee",
        avatar: "https://res.cloudinary.com/tinyfac-es/image/upload/w_1024,h_1024,c_fit/v1627199987/facebook/yqbfbicwl4rygivfvxv7.jpg",
        image: "https://picsum.photos/600?random=122",
        favorite: false,
        likes: 6805,
        dislikes: 216,
        quote: "We must embrace pain and burn it as fuel for our journey.",
    },
    {
        id: 32,
        firstName: "Dawna",
        lastName: "Lapadula",
        avatar: "https://res.cloudinary.com/tinyfac-es/image/upload/w_1024,h_1024,c_fit/v1627200035/facebook/wnduuupvqmpay73ievyg.jpg",
        image: "https://picsum.photos/600?random=102",
        favorite: false,
        likes: 2946,
        dislikes: 363,
        quote: "Wrinkles should merely indicate where smiles have been.",
    },
    {
        id: 33,
        firstName: "Katusha",
        lastName: "Sroczynski",
        avatar: "https://res.cloudinary.com/tinyfac-es/image/upload/w_1024,h_1024,c_fit/v1627200073/facebook/hegbnyjmxlnznd90ck0z.jpg",
        image: "https://picsum.photos/600?random=192",
        favorite: false,
        likes: 6762,
        dislikes: 451,
        quote: "The beginning is always today.",
    },
    {
        id: 34,
        firstName: "Ansell",
        lastName: "Deline",
        avatar: "https://res.cloudinary.com/tinyfac-es/image/upload/w_1024,h_1024,c_fit/v1627200084/facebook/phzrxcd5ld9qytsd0pzg.jpg",
        image: "https://picsum.photos/600?random=263",
        favorite: false,
        likes: 5258,
        dislikes: 288,
        quote: "A friend is, as it were, a second self.",
    },
    {
        id: 35,
        firstName: "Ansell",
        lastName: "Deline",
        avatar: "https://res.cloudinary.com/tinyfac-es/image/upload/w_1024,h_1024,c_fit/v1627200084/facebook/phzrxcd5ld9qytsd0pzg.jpg",
        image: "https://picsum.photos/600?random=288",
        favorite: false,
        likes: 4249,
        dislikes: 396,
        quote: "Yesterday’s home runs don't win today's games.",
    },
    {
        id: 36,
        firstName: "Lazlo",
        lastName: "Grippi",
        avatar: "https://res.cloudinary.com/tinyfac-es/image/upload/w_1024,h_1024,c_fit/v1627199986/facebook/cyritfbaorr1wxaqoxy3.jpg",
        image: "https://picsum.photos/600?random=299",
        favorite: false,
        likes: 5907,
        dislikes: 85,
        quote: "Study the past, if you would divine the future.",
    },
    {
        id: 37,
        firstName: "Ginevra",
        lastName: "Prudente",
        avatar: "https://res.cloudinary.com/tinyfac-es/image/upload/w_1024,h_1024,c_fit/v1627200088/facebook/styqmwjicrj80zphxzuu.jpg",
        image: "https://picsum.photos/600?random=125",
        favorite: false,
        likes: 4361,
        dislikes: 140,
        quote: "Wherever you go, go with all your heart.",
    },
    {
        id: 38,
        firstName: "Berthe",
        lastName: "Hrobsky",
        avatar: "https://res.cloudinary.com/tinyfac-es/image/upload/w_1024,h_1024,c_fit/v1627199943/facebook/ggfttwzxpakh4mfh3oy2.jpg",
        image: "https://picsum.photos/600?random=232",
        favorite: false,
        likes: 5203,
        dislikes: 497,
        quote: "It is fatal to enter any war without the will to win it.",
    },
    {
        id: 39,
        firstName: "Dawna",
        lastName: "Lapadula",
        avatar: "https://res.cloudinary.com/tinyfac-es/image/upload/w_1024,h_1024,c_fit/v1627200035/facebook/wnduuupvqmpay73ievyg.jpg",
        image: "https://picsum.photos/600?random=5",
        favorite: false,
        likes: 6600,
        dislikes: 489,
        quote: "The eye sees only what the mind is prepared to comprehend.",
    },
    {
        id: 40,
        firstName: "Rosalynd",
        lastName: "Ibbetson",
        avatar: "https://res.cloudinary.com/tinyfac-es/image/upload/w_1024,h_1024,c_fit/v1627200051/facebook/s3zdxnpt0cnfkiklnbzg.jpg",
        image: "https://picsum.photos/600?random=229",
        favorite: false,
        likes: 6844,
        dislikes: 89,
        quote: "Don't smother each other. No one can grow in the shade.",
    },
    {
        id: 41,
        firstName: "Suzan",
        lastName: "Vaile",
        avatar: "https://res.cloudinary.com/tinyfac-es/image/upload/w_1024,h_1024,c_fit/v1627199959/facebook/tvus4imfl2p4reywn8g7.jpg",
        image: "https://picsum.photos/600?random=70",
        favorite: false,
        likes: 4821,
        dislikes: 416,
        quote: "Love is a serious mental disease.",
    },
    {
        id: 42,
        firstName: "Berthe",
        lastName: "Hrobsky",
        avatar: "https://res.cloudinary.com/tinyfac-es/image/upload/w_1024,h_1024,c_fit/v1627199943/facebook/ggfttwzxpakh4mfh3oy2.jpg",
        image: "https://picsum.photos/600?random=133",
        favorite: false,
        likes: 3211,
        dislikes: 181,
        quote: "Our distrust is very expensive.",
    },
    {
        id: 43,
        firstName: "Julienne",
        lastName: "Sauby",
        avatar: "https://res.cloudinary.com/tinyfac-es/image/upload/w_1024,h_1024,c_fit/v1627200025/facebook/gabblg9ryccmkjkqe20w.jpg",
        image: "https://picsum.photos/600?random=38",
        favorite: false,
        likes: 3491,
        dislikes: 213,
        quote: "To bring anything into your life, imagine that it's already there.",
    },
    {
        id: 44,
        firstName: "Mace",
        lastName: "Unsworth",
        avatar: "https://res.cloudinary.com/tinyfac-es/image/upload/w_1024,h_1024,c_fit/v1627199954/facebook/iwojahajoulb3iw3fmgs.jpg",
        image: "https://picsum.photos/600?random=48",
        favorite: false,
        likes: 6087,
        dislikes: 374,
        quote: "The invariable mark of wisdom is to see the miraculous in the common.",
    },
    {
        id: 45,
        firstName: "Berthe",
        lastName: "Hrobsky",
        avatar: "https://res.cloudinary.com/tinyfac-es/image/upload/w_1024,h_1024,c_fit/v1627199943/facebook/ggfttwzxpakh4mfh3oy2.jpg",
        image: "https://picsum.photos/600?random=42",
        favorite: false,
        likes: 5090,
        dislikes: 415,
        quote: "The greatest gift of life is friendship, and I have received it.",
    },
    {
        id: 46,
        firstName: "Cecil",
        lastName: "Hoglan",
        avatar: "https://res.cloudinary.com/tinyfac-es/image/upload/w_1024,h_1024,c_fit/v1627199965/facebook/jh74nclyizzljedb94bt.jpg",
        image: "https://picsum.photos/600?random=182",
        favorite: false,
        likes: 4321,
        dislikes: 464,
        quote: "The friendship that can cease has never been real.",
    },
    {
        id: 47,
        firstName: "Roxanne",
        lastName: "Mcleese",
        avatar: "https://res.cloudinary.com/tinyfac-es/image/upload/w_1024,h_1024,c_fit/v1627199963/facebook/x88dl9hfzhvtsly9r546.jpg",
        image: "https://picsum.photos/600?random=57",
        favorite: false,
        likes: 5626,
        dislikes: 183,
        quote: "One may say the eternal mystery of the world is its comprehensibility.",
    },
    {
        id: 48,
        firstName: "Ayn",
        lastName: "Agard",
        avatar: "https://res.cloudinary.com/tinyfac-es/image/upload/w_1024,h_1024,c_fit/v1627200074/facebook/xzycmappzltk39swt5wz.jpg",
        image: "https://picsum.photos/600?random=215",
        favorite: false,
        likes: 3279,
        dislikes: 261,
        quote: "There is no failure except in no longer trying.",
    },
    {
        id: 49,
        firstName: "Tiff",
        lastName: "Treen",
        avatar: "https://res.cloudinary.com/tinyfac-es/image/upload/w_1024,h_1024,c_fit/v1627199961/facebook/tm4a7psa2yyztvgs8dox.jpg",
        image: "https://picsum.photos/600?random=24",
        favorite: false,
        likes: 3513,
        dislikes: 319,
        quote: "There is no greater harm than that of time wasted.",
    },
    {
        id: 50,
        firstName: "Lissi",
        lastName: "Tocchio",
        avatar: "https://res.cloudinary.com/tinyfac-es/image/upload/w_1024,h_1024,c_fit/v1627200002/facebook/e6nfzs1jsv9ngzjivheb.jpg",
        image: "https://picsum.photos/600?random=92",
        favorite: false,
        likes: 3080,
        dislikes: 90,
        quote: "Ideas are the beginning points of all fortunes.",
    },
    {
        id: 51,
        firstName: "Julienne",
        lastName: "Sauby",
        avatar: "https://res.cloudinary.com/tinyfac-es/image/upload/w_1024,h_1024,c_fit/v1627200025/facebook/gabblg9ryccmkjkqe20w.jpg",
        image: "https://picsum.photos/600?random=31",
        favorite: false,
        likes: 6737,
        dislikes: 140,
        quote: "Nothing ever goes away until it has taught us what we need to know.",
    },
    {
        id: 52,
        firstName: "Rosabelle",
        lastName: "Stagers",
        avatar: "https://res.cloudinary.com/tinyfac-es/image/upload/w_1024,h_1024,c_fit/v1627200025/facebook/ox8s35tv185lb7dw8el0.jpg",
        image: "https://picsum.photos/600?random=87",
        favorite: false,
        likes: 5799,
        dislikes: 71,
        quote: "Excellence is not a skill. It is an attitude.",
    },
    {
        id: 53,
        firstName: "Katusha",
        lastName: "Sroczynski",
        avatar: "https://res.cloudinary.com/tinyfac-es/image/upload/w_1024,h_1024,c_fit/v1627200073/facebook/hegbnyjmxlnznd90ck0z.jpg",
        image: "https://picsum.photos/600?random=25",
        favorite: false,
        likes: 6014,
        dislikes: 178,
        quote: "Where there is great love, there are always miracles.",
    },
    {
        id: 54,
        firstName: "Chastity",
        lastName: "Speir",
        avatar: "https://res.cloudinary.com/tinyfac-es/image/upload/w_1024,h_1024,c_fit/v1627199936/facebook/z5jkejtavbbalgw8ho9a.jpg",
        image: "https://picsum.photos/600?random=270",
        favorite: false,
        likes: 4363,
        dislikes: 326,
        quote: "Never interrupt your enemy when he is making a mistake.",
    },
    {
        id: 55,
        firstName: "Sharron",
        lastName: "Mclilly",
        avatar: "https://res.cloudinary.com/tinyfac-es/image/upload/w_1024,h_1024,c_fit/v1627200032/facebook/sc2kw3evr2ffwl8crlkk.jpg",
        image: "https://picsum.photos/600?random=126",
        favorite: false,
        likes: 4327,
        dislikes: 378,
        quote: "Not engaging in ignorance is wisdom.",
    },
    {
        id: 56,
        firstName: "Roxanne",
        lastName: "Mcleese",
        avatar: "https://res.cloudinary.com/tinyfac-es/image/upload/w_1024,h_1024,c_fit/v1627199963/facebook/x88dl9hfzhvtsly9r546.jpg",
        image: "https://picsum.photos/600?random=209",
        favorite: false,
        likes: 4505,
        dislikes: 252,
        quote: "Wisdom has its root in goodness, not goodness its root in wisdom.",
    },
    {
        id: 57,
        firstName: "Sheilakathryn",
        lastName: "Fernandz",
        avatar: "https://res.cloudinary.com/tinyfac-es/image/upload/w_1024,h_1024,c_fit/v1627200025/facebook/aopuw2ptal2kt9cf3hcp.jpg",
        image: "https://picsum.photos/600?random=71",
        favorite: false,
        likes: 6438,
        dislikes: 399,
        quote: "A quarrel between friends, when made up, adds a new tie to friendship.",
    },
    {
        id: 58,
        firstName: "Jameson",
        lastName: "Bologna",
        avatar: "https://res.cloudinary.com/tinyfac-es/image/upload/w_1024,h_1024,c_fit/v1627199928/facebook/dqqpq30cor22i9t9whwd.jpg",
        image: "https://picsum.photos/600?random=77",
        favorite: false,
        likes: 3086,
        dislikes: 337,
        quote: "Better than a thousand hollow words, is one word that brings peace.",
    },
    {
        id: 59,
        firstName: "Malanie",
        lastName: "Malak",
        avatar: "https://res.cloudinary.com/tinyfac-es/image/upload/w_1024,h_1024,c_fit/v1627200043/facebook/esqf0ilj4r3siucffj19.jpg",
        image: "https://picsum.photos/600?random=194",
        favorite: false,
        likes: 4548,
        dislikes: 56,
        quote: "The heart has eyes which the brain knows nothing of.",
    },
    {
        id: 60,
        firstName: "Nanni",
        lastName: "Riopel",
        avatar: "https://res.cloudinary.com/tinyfac-es/image/upload/w_1024,h_1024,c_fit/v1627199948/facebook/gfvwrkz9muttrnquixqj.jpg",
        image: "https://picsum.photos/600?random=156",
        favorite: false,
        likes: 2534,
        dislikes: 291,
        quote: "Don't be afraid to go out on a limb. That's where the fruit is.",
    },
    {
        id: 61,
        firstName: "Lissi",
        lastName: "Tocchio",
        avatar: "https://res.cloudinary.com/tinyfac-es/image/upload/w_1024,h_1024,c_fit/v1627200002/facebook/e6nfzs1jsv9ngzjivheb.jpg",
        image: "https://picsum.photos/600?random=197",
        favorite: false,
        likes: 5755,
        dislikes: 434,
        quote: "I have often regretted my speech, never my silence.",
    },
    {
        id: 62,
        firstName: "Julienne",
        lastName: "Sauby",
        avatar: "https://res.cloudinary.com/tinyfac-es/image/upload/w_1024,h_1024,c_fit/v1627200025/facebook/gabblg9ryccmkjkqe20w.jpg",
        image: "https://picsum.photos/600?random=49",
        favorite: false,
        likes: 4571,
        dislikes: 95,
        quote: "You teach best what you most need to learn.",
    },
    {
        id: 63,
        firstName: "Eula",
        lastName: "Bervig",
        avatar: "https://res.cloudinary.com/tinyfac-es/image/upload/w_1024,h_1024,c_fit/v1627199965/facebook/jpqucagqc1nhwvtxa59i.jpg",
        image: "https://picsum.photos/600?random=33",
        favorite: false,
        likes: 3883,
        dislikes: 377,
        quote: "It is the neglect of timely repair that makes rebuilding necessary.",
    },
    {
        id: 64,
        firstName: "Nanni",
        lastName: "Riopel",
        avatar: "https://res.cloudinary.com/tinyfac-es/image/upload/w_1024,h_1024,c_fit/v1627199948/facebook/gfvwrkz9muttrnquixqj.jpg",
        image: "https://picsum.photos/600?random=249",
        favorite: false,
        likes: 3091,
        dislikes: 462,
        quote: "If you want to go east, don't go west.",
    },
    {
        id: 65,
        firstName: "Sharron",
        lastName: "Mclilly",
        avatar: "https://res.cloudinary.com/tinyfac-es/image/upload/w_1024,h_1024,c_fit/v1627200032/facebook/sc2kw3evr2ffwl8crlkk.jpg",
        image: "https://picsum.photos/600?random=220",
        favorite: false,
        likes: 6602,
        dislikes: 268,
        quote: "Computers are like bikinis. They save people a lot of guesswork.",
    },
    {
        id: 66,
        firstName: "Ansell",
        lastName: "Deline",
        avatar: "https://res.cloudinary.com/tinyfac-es/image/upload/w_1024,h_1024,c_fit/v1627200084/facebook/phzrxcd5ld9qytsd0pzg.jpg",
        image: "https://picsum.photos/600?random=91",
        favorite: false,
        likes: 4020,
        dislikes: 471,
        quote: "Blessed are the hearts that can bend; they shall never be broken.",
    },
    {
        id: 67,
        firstName: "Candida",
        lastName: "Liedy",
        avatar: "https://res.cloudinary.com/tinyfac-es/image/upload/w_1024,h_1024,c_fit/v1627199971/facebook/tggdxxxdscj9vlntfkkf.jpg",
        image: "https://picsum.photos/600?random=228",
        favorite: false,
        likes: 4140,
        dislikes: 380,
        quote: "We make our own fortunes and we call them fate.",
    },
    {
        id: 68,
        firstName: "Katusha",
        lastName: "Sroczynski",
        avatar: "https://res.cloudinary.com/tinyfac-es/image/upload/w_1024,h_1024,c_fit/v1627200073/facebook/hegbnyjmxlnznd90ck0z.jpg",
        image: "https://picsum.photos/600?random=256",
        favorite: false,
        likes: 6196,
        dislikes: 421,
        quote: "Life isn't about finding yourself. Life is about creating yourself.",
    },
    {
        id: 69,
        firstName: "Neall",
        lastName: "Awkard",
        avatar: "https://res.cloudinary.com/tinyfac-es/image/upload/w_1024,h_1024,c_fit/v1627200015/facebook/ah8r4kdkc0ieonk4wfko.jpg",
        image: "https://picsum.photos/600?random=30",
        favorite: false,
        likes: 3855,
        dislikes: 412,
        quote: "The cautious seldom err.",
    },
    {
        id: 70,
        firstName: "Malvina",
        lastName: "Patrylak",
        avatar: "https://res.cloudinary.com/tinyfac-es/image/upload/w_1024,h_1024,c_fit/v1627199961/facebook/dpfnqrieeve3rh3xqy0a.jpg",
        image: "https://picsum.photos/600?random=277",
        favorite: false,
        likes: 2803,
        dislikes: 479,
        quote: "Never mistake motion for action.",
    },
    {
        id: 71,
        firstName: "Sharron",
        lastName: "Mclilly",
        avatar: "https://res.cloudinary.com/tinyfac-es/image/upload/w_1024,h_1024,c_fit/v1627200032/facebook/sc2kw3evr2ffwl8crlkk.jpg",
        image: "https://picsum.photos/600?random=38",
        favorite: false,
        likes: 6682,
        dislikes: 312,
        quote: "If there is no struggle, there is no progress.",
    },
    {
        id: 72,
        firstName: "Katusha",
        lastName: "Sroczynski",
        avatar: "https://res.cloudinary.com/tinyfac-es/image/upload/w_1024,h_1024,c_fit/v1627200073/facebook/hegbnyjmxlnznd90ck0z.jpg",
        image: "https://picsum.photos/600?random=87",
        favorite: false,
        likes: 3241,
        dislikes: 328,
        quote: "Life is what happens while you are making other plans.",
    },
    {
        id: 73,
        firstName: "Sheilakathryn",
        lastName: "Fernandz",
        avatar: "https://res.cloudinary.com/tinyfac-es/image/upload/w_1024,h_1024,c_fit/v1627200025/facebook/aopuw2ptal2kt9cf3hcp.jpg",
        image: "https://picsum.photos/600?random=39",
        favorite: false,
        likes: 4336,
        dislikes: 298,
        quote: "Life without love is like a tree without blossoms or fruit.",
    },
    {
        id: 74,
        firstName: "Mace",
        lastName: "Unsworth",
        avatar: "https://res.cloudinary.com/tinyfac-es/image/upload/w_1024,h_1024,c_fit/v1627199954/facebook/iwojahajoulb3iw3fmgs.jpg",
        image: "https://picsum.photos/600?random=202",
        favorite: false,
        likes: 3109,
        dislikes: 252,
        quote: "Stay committed to your decisions, but stay flexible in your approach.",
    },
    {
        id: 75,
        firstName: "Berthe",
        lastName: "Hrobsky",
        avatar: "https://res.cloudinary.com/tinyfac-es/image/upload/w_1024,h_1024,c_fit/v1627199943/facebook/ggfttwzxpakh4mfh3oy2.jpg",
        image: "https://picsum.photos/600?random=283",
        favorite: false,
        likes: 4577,
        dislikes: 358,
        quote: "Technology is a word that describes something that doesn’t work yet.",
    },
    {
        id: 76,
        firstName: "Nanni",
        lastName: "Riopel",
        avatar: "https://res.cloudinary.com/tinyfac-es/image/upload/w_1024,h_1024,c_fit/v1627199948/facebook/gfvwrkz9muttrnquixqj.jpg",
        image: "https://picsum.photos/600?random=197",
        favorite: false,
        likes: 3857,
        dislikes: 326,
        quote: "I hear and I forget. I see and I remember. I do and I understand.",
    },
    {
        id: 77,
        firstName: "Ginevra",
        lastName: "Prudente",
        avatar: "https://res.cloudinary.com/tinyfac-es/image/upload/w_1024,h_1024,c_fit/v1627200088/facebook/styqmwjicrj80zphxzuu.jpg",
        image: "https://picsum.photos/600?random=102",
        favorite: false,
        likes: 3380,
        dislikes: 163,
        quote: "Friends show their love in times of trouble, not in happiness.",
    },
    {
        id: 78,
        firstName: "Lucy",
        lastName: "Cardona",
        avatar: "https://res.cloudinary.com/tinyfac-es/image/upload/w_1024,h_1024,c_fit/v1627200008/facebook/t8tobjxzavpi68dus04t.jpg",
        image: "https://picsum.photos/600?random=281",
        favorite: false,
        likes: 2772,
        dislikes: 390,
        quote: "You cannot be lonely if you like the person you're alone with.",
    },
    {
        id: 79,
        firstName: "Sharai",
        lastName: "Deslatte",
        avatar: "https://res.cloudinary.com/tinyfac-es/image/upload/w_1024,h_1024,c_fit/v1627199953/facebook/hxfzz3fs8ancpuqdahtk.jpg",
        image: "https://picsum.photos/600?random=295",
        favorite: false,
        likes: 4850,
        dislikes: 126,
        quote: "God has given you one face, and you make yourself another.",
    },
    {
        id: 80,
        firstName: "Jonny",
        lastName: "Lacrue",
        avatar: "https://res.cloudinary.com/tinyfac-es/image/upload/w_1024,h_1024,c_fit/v1627200011/facebook/ew3gzts99dtl2s4vzwjj.jpg",
        image: "https://picsum.photos/600?random=215",
        favorite: false,
        likes: 2554,
        dislikes: 440,
        quote: "The truth is not for all men, but only for those who seek it.",
    },
    {
        id: 81,
        firstName: "Julienne",
        lastName: "Sauby",
        avatar: "https://res.cloudinary.com/tinyfac-es/image/upload/w_1024,h_1024,c_fit/v1627200025/facebook/gabblg9ryccmkjkqe20w.jpg",
        image: "https://picsum.photos/600?random=41",
        favorite: false,
        likes: 3452,
        dislikes: 443,
        quote: "The human spirit must prevail over technology.",
    },
    {
        id: 82,
        firstName: "Lucy",
        lastName: "Cardona",
        avatar: "https://res.cloudinary.com/tinyfac-es/image/upload/w_1024,h_1024,c_fit/v1627200008/facebook/t8tobjxzavpi68dus04t.jpg",
        image: "https://picsum.photos/600?random=210",
        favorite: false,
        likes: 6303,
        dislikes: 490,
        quote: "Friends are the siblings God never gave us.",
    },
    {
        id: 83,
        firstName: "Emil",
        lastName: "Mccranie",
        avatar: "https://res.cloudinary.com/tinyfac-es/image/upload/w_1024,h_1024,c_fit/v1627200028/facebook/jfauh2lwhqumj0ijce38.jpg",
        image: "https://picsum.photos/600?random=124",
        favorite: false,
        likes: 3452,
        dislikes: 82,
        quote: "You win the victory when you yield to friends.",
    },
    {
        id: 84,
        firstName: "Eula",
        lastName: "Bervig",
        avatar: "https://res.cloudinary.com/tinyfac-es/image/upload/w_1024,h_1024,c_fit/v1627199965/facebook/jpqucagqc1nhwvtxa59i.jpg",
        image: "https://picsum.photos/600?random=104",
        favorite: false,
        likes: 6834,
        dislikes: 216,
        quote: "Friendship is Love without his wings!",
    },
    {
        id: 85,
        firstName: "Berthe",
        lastName: "Hrobsky",
        avatar: "https://res.cloudinary.com/tinyfac-es/image/upload/w_1024,h_1024,c_fit/v1627199943/facebook/ggfttwzxpakh4mfh3oy2.jpg",
        image: "https://picsum.photos/600?random=185",
        favorite: false,
        likes: 6852,
        dislikes: 349,
        quote: "Logic will get you from A to B. Imagination will take you everywhere.",
    },
    {
        id: 86,
        firstName: "Zebedee",
        lastName: "Busenius",
        avatar: "https://res.cloudinary.com/tinyfac-es/image/upload/w_1024,h_1024,c_fit/v1630596435/facebook/rw9x7plxcpgwtzmk6p37.jpg",
        image: "https://picsum.photos/600?random=59",
        favorite: false,
        likes: 2980,
        dislikes: 377,
        quote: "One today is worth two tomorrows.",
    },
    {
        id: 87,
        firstName: "Jameson",
        lastName: "Bologna",
        avatar: "https://res.cloudinary.com/tinyfac-es/image/upload/w_1024,h_1024,c_fit/v1627199928/facebook/dqqpq30cor22i9t9whwd.jpg",
        image: "https://picsum.photos/600?random=122",
        favorite: false,
        likes: 5948,
        dislikes: 280,
        quote: "A man is not old as long as he is seeking something.",
    },
    {
        id: 88,
        firstName: "Lissi",
        lastName: "Tocchio",
        avatar: "https://res.cloudinary.com/tinyfac-es/image/upload/w_1024,h_1024,c_fit/v1627200002/facebook/e6nfzs1jsv9ngzjivheb.jpg",
        image: "https://picsum.photos/600?random=169",
        favorite: false,
        likes: 6357,
        dislikes: 468,
        quote: "A single rose can be my garden... a single friend, my world.",
    },
    {
        id: 89,
        firstName: "Lazlo",
        lastName: "Grippi",
        avatar: "https://res.cloudinary.com/tinyfac-es/image/upload/w_1024,h_1024,c_fit/v1627199986/facebook/cyritfbaorr1wxaqoxy3.jpg",
        image: "https://picsum.photos/600?random=110",
        favorite: false,
        likes: 6384,
        dislikes: 188,
        quote: "Don't settle for a relationship that won't let you be yourself.",
    },
    {
        id: 90,
        firstName: "Rosalynd",
        lastName: "Ibbetson",
        avatar: "https://res.cloudinary.com/tinyfac-es/image/upload/w_1024,h_1024,c_fit/v1627200051/facebook/s3zdxnpt0cnfkiklnbzg.jpg",
        image: "https://picsum.photos/600?random=166",
        favorite: false,
        likes: 5358,
        dislikes: 444,
        quote: "The best way out is always through.",
    },
    {
        id: 91,
        firstName: "Suzan",
        lastName: "Vaile",
        avatar: "https://res.cloudinary.com/tinyfac-es/image/upload/w_1024,h_1024,c_fit/v1627199959/facebook/tvus4imfl2p4reywn8g7.jpg",
        image: "https://picsum.photos/600?random=229",
        favorite: false,
        likes: 3150,
        dislikes: 195,
        quote: "If we did the things we are capable of, we would astound ourselves.",
    },
    {
        id: 92,
        firstName: "Jonny",
        lastName: "Lacrue",
        avatar: "https://res.cloudinary.com/tinyfac-es/image/upload/w_1024,h_1024,c_fit/v1627200011/facebook/ew3gzts99dtl2s4vzwjj.jpg",
        image: "https://picsum.photos/600?random=206",
        favorite: false,
        likes: 2796,
        dislikes: 492,
        quote: "If you surrender to the wind, you can ride it.",
    },
    {
        id: 93,
        firstName: "Pepi",
        lastName: "Hutchings",
        avatar: "https://res.cloudinary.com/tinyfac-es/image/upload/w_1024,h_1024,c_fit/v1627199970/facebook/g1vbmsmohrypg3aqt8ig.jpg",
        image: "https://picsum.photos/600?random=26",
        favorite: false,
        likes: 6449,
        dislikes: 356,
        quote: "It always seems impossible until it's done.",
    },
    {
        id: 94,
        firstName: "Berthe",
        lastName: "Hrobsky",
        avatar: "https://res.cloudinary.com/tinyfac-es/image/upload/w_1024,h_1024,c_fit/v1627199943/facebook/ggfttwzxpakh4mfh3oy2.jpg",
        image: "https://picsum.photos/600?random=265",
        favorite: false,
        likes: 6355,
        dislikes: 235,
        quote: "Technology has to be invented or adopted.",
    },
    {
        id: 95,
        firstName: "Julienne",
        lastName: "Sauby",
        avatar: "https://res.cloudinary.com/tinyfac-es/image/upload/w_1024,h_1024,c_fit/v1627200025/facebook/gabblg9ryccmkjkqe20w.jpg",
        image: "https://picsum.photos/600?random=178",
        favorite: false,
        likes: 2588,
        dislikes: 414,
        quote: "Work out your own salvation. Do not depend on others.",
    },
    {
        id: 96,
        firstName: "Lonna",
        lastName: "Hannay",
        avatar: "https://res.cloudinary.com/tinyfac-es/image/upload/w_1024,h_1024,c_fit/v1627199978/facebook/aizmg0ko2hzrzbxl3lpb.jpg",
        image: "https://picsum.photos/600?random=45",
        favorite: false,
        likes: 6256,
        dislikes: 488,
        quote: "The way is not in the sky. The way is in the heart.",
    },
    {
        id: 97,
        firstName: "Sharai",
        lastName: "Deslatte",
        avatar: "https://res.cloudinary.com/tinyfac-es/image/upload/w_1024,h_1024,c_fit/v1627199953/facebook/hxfzz3fs8ancpuqdahtk.jpg",
        image: "https://picsum.photos/600?random=101",
        favorite: false,
        likes: 6340,
        dislikes: 463,
        quote: "What is not started today is never finished tomorrow.",
    },
    {
        id: 98,
        firstName: "Shaun",
        lastName: "Metzler",
        avatar: "https://res.cloudinary.com/tinyfac-es/image/upload/w_1024,h_1024,c_fit/v1627199968/facebook/bbx8qe8t8glardtvdgmh.jpg",
        image: "https://picsum.photos/600?random=8",
        favorite: false,
        likes: 5855,
        dislikes: 277,
        quote: "Loss is nothing else but change, and change is Nature’s delight.",
    },
    {
        id: 99,
        firstName: "Roxanne",
        lastName: "Mcleese",
        avatar: "https://res.cloudinary.com/tinyfac-es/image/upload/w_1024,h_1024,c_fit/v1627199963/facebook/x88dl9hfzhvtsly9r546.jpg",
        image: "https://picsum.photos/600?random=276",
        favorite: false,
        likes: 3010,
        dislikes: 100,
        quote: "Nature is a mutable cloud which is always and never the same.",
    },
];
